## Site ========================================================================
url: https://choens.github.io/blood-sugars/
name: Blood Sugars
description: An Exploration Of Nightscout CGM Data

# What exactly does this do?
#pages_list:       
#  About: '/about'
#  Blog: '/blog'
#  RSS: '/rss.xml'



## About Me ====================================================================
author: Andy Choens
email: andy.choens@gmail.com
github: Choens



## Config ======================================================================

# Markdown Engine --------------------------------------------------------------
markdown: kramdown

# Permalinks -------------------------------------------------------------------
permalink: date

# Number of articles do you wish to appear on the front page -------------------
paginate: 7

# Exclude metadata and development time dependencies ---------------------------
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Syntax Hightlingt ------------------------------------------------------------
syntax-highlighting:
  enabled: true
  css: syntax.css